version: '3'


# Network
networks: 
  casocavallo_network:
    ipam:
      config: 
        - subnet: 1.0.0.0/24 


# Services
services: 

  # Random generator
  casocavallo_random_generator:
    build: './RandomGenerator'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.11'
    volumes: 
      - './RandomGenerator:/app/casocavallo/random_generator'
    command: ['python', 'Generator.py']

  # Redis server
  casocavallo_redis:
    build: './Redis'
    ports: 
      - '6379:6379'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.10'   
    command: [ 'redis-server', '/usr/local/etc/redis/redis.conf' ]

  # Experimental P2P Layer - server
  casocavallo_experimental_p2p_layer_server:
    build: './EXPERIMENTAL_P2PLayer'
    volumes: 
      - './EXPERIMENTAL_P2PLayer:/app/casocavallo/p2p_layer'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.12'
    command: [ 'npm', 'run', 'server' ]

  # Experimental P2P Layer - client
  casocavallo_experimental_p2p_layer_client:
    build: './EXPERIMENTAL_P2PLayer'
    volumes: 
      - './EXPERIMENTAL_P2PLayer:/app/casocavallo/p2p_layer'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.13'
    command: [ 'npm', 'run', 'client' ]


